### ISSUE TITLE
Setting images folder

### ISSUE THREAD

**Issue by omairvaiyani** [ramybenaroya/ember-cli-lightbox#14]
I use fingerprinting and have a specific folder for my images. Is it possible to define what path the following images are set to:

- /images/lightbox/close.png
- /images/lightbox/loading.gif
- /images/lightbox/next.png
- /images/lightbox/prev.png

I currently store my images at /img/*

**Comment by ramybenaroya** [comment]
Currenty the addon copies Lightbox's images from `./node_modules/lightbox2/dist/images` to `assets/images/lightbox`. This is done [here](https://github.com/ramybenaroya/ember-cli-lightbox/blob/master/index.js#L10).
Do you mean that you want to config these images location?   
Is that because you don't want to have an "alien" folder named `assets/images` next to your `assets/img` folder?

**Comment by ramybenaroya** [comment]
Closed due to lack of response
